### ISSUE TITLE
安装完成机器人后QQ群内无法使用

### ISSUE THREAD

**Issue by Sualiu** [RicheyJang/PaimengBot#1]
如题，只能单独对话时有用，QQ群里无效果。

**Comment by Sualiu** [comment]
文档里面似乎没有准确说明如何启用QQ群之类的（也可能眼瞎）

**Comment by RicheyJang** [comment]
为了防止派蒙Bot在群聊中乱答话，在群聊中调用它请加上它的名字前缀。例如：`派蒙帮助`、`派蒙关闭复读`。
![Screenshot_20220202_204009_com tencent mobileqq_edit_469243041801313](https://user-images.githubusercontent.com/48620068/152156338-3b141270-d222-4254-8d23-ffa4a3aa0838.jpg)
在私聊中无需加上名字前缀。
如果加了名字前缀也没有反应，一般来说是被QQ风控了(无法通过cqhttp虚拟设备在群中正常发消息)，请参照go-cqhttp端日志和文档，风控问题机器人开发方无法解决，需要换账号或尝试挂3-7天。

**Comment by RicheyJang** [comment]
> 文档里面似乎没有准确说明如何启用QQ群之类的（也可能眼瞎）

抱歉，上述回复我后续会在文档中加以说明

**Comment by Sualiu** [comment]
谢谢！

**Comment by uuyun** [comment]
希望增加对接自定义api和群关键词撤回

**Comment by RicheyJang** [comment]
> 希望增加对接自定义api和群关键词撤回

需求相关请加群提出，或创建新的issue，不要在已关闭的issue中提出新需求，谢谢。
在群中可以直接提出需求，并与群友讨论完善，我一般都会采纳并在新版本中发布。

**Comment by yellowpeachxgp** [comment]
群找不到哇>o<怎么办
