### ISSUE TITLE
可以把好康的功能改为私聊发送吗？

### ISSUE THREAD

**Issue by fivefirex** [RicheyJang/PaimengBot#12]
群里一堆人捣乱，我怕哪天有人给我举报了，谢谢

**Comment by RicheyJang** [comment]
派蒙Bot带有功能开关、封禁功能，在想关闭"好康的"功能的群中发送`派蒙关闭好康的`即可在该群中关闭"好康的"功能。其它操作参见`帮助 功能开关`。
