### ISSUE TITLE
可以出一个微信版本的吗

### ISSUE THREAD

**Issue by myshine1605** [RicheyJang/PaimengBot#15]

**Comment by RicheyJang** [comment]
暂时没有支持微信的计划，因为有很多功能例如群管理、关键词撤回、图片回复等，在微信上并不支持，有碍于机器人整体的使用。
但终归而言，Paimeng是基于OneBot协议实现的，它并不针对某一特定的聊天APP，只要你可以找到一个微信的Onebot前端实现，Paimeng是照样可以对接上的。
