### ISSUE TITLE
关于财富系统cost插件的问题

### ISSUE THREAD

**Issue by Just1ceCATT** [RicheyJang/PaimengBot#16]
在机器人的帮助->签到与财富 中看到说明，配置 plugin 文件中的插件 key.cost 配置项就可以设置指定插件的花费。
但是我在 plugin 文件中没有找到cost插件，是未开发完成还是我的机器人版本未更新？在机器人检查更新功能中显示我的机器人已经是最新版了
如果是未开发完成，那预计完成时间是什么时候？如果是未更新，更新渠道在哪里？程序是否支持自动更新？

**Comment by RicheyJang** [comment]
所有你可以在帮助里看到的功能都是完全开发完毕且开放的，包括财富系统。
默认情况下，大部分插件并没有直接填写好cost配置项，但所有插件（除了极少部分特殊插件，例如聊天）都支持配置cost，你只需要自己给想加以花费的插件加上一个cost配置项即可，例如：
```yaml
translate:
  cost: 0.5
...
```
