### ISSUE TITLE
眼神暗示，能不能官方编译个arm64版本用在树莓派上

### ISSUE THREAD

**Issue by SoraKasvgano** [RicheyJang/PaimengBot#2]
眼神暗示，能不能官方编译个arm64版本用在树莓派上2333

**Comment by RicheyJang** [comment]
由于SQLite支持部分使用了CGO，难以交叉编译，因此暂不提供ARM64的官方版本，敬请谅解。
可以自行下载go环境，自行编译；若懒得自己编译，可以加群向我索要不支持SQLite的各种可执行版本（包括但不限于ARM64）。

**Comment by RicheyJang** [comment]
v0.1.4+版本摆脱了CGO的SQLite，因此目前已官方提供Linux-arm64发布版本，参见release
