### ISSUE TITLE
请问这机器人如何安装其他的插件

### ISSUE THREAD

**Issue by Xenolies** [RicheyJang/PaimengBot#5]
比如获取崩坏三信息的这种

**Comment by RicheyJang** [comment]
只要是符合派蒙Bot开发规范的插件，只需将其放入plugins文件夹，并在main.go文件中匿名引入即可。
如有新需求，请加群提出；如插件已经开发完成，可以提交PR。
开发文档：https://richeyjang.github.io/PaimengBot/develop/

**Comment by Xenolies** [comment]
> 



> 只要是符合派蒙Bot开发规范的插件，只需将其放入plugins文件夹，并在main.go文件中匿名引入即可。 如有新需求，请加群提出；如插件已经开发完成，可以提交PR。 开发文档：https://richeyjang.github.io/PaimengBot/develop/
感谢，这几天看了下go语言的语法，正好和我现在学的JAVA语言差别不大，想试试看来着。

**Comment by RicheyJang** [comment]
派蒙Bot的插件封装还是比较完备的，utils中也提供了大量工具函数，欢迎参照开发文档开发插件并提交PR，可以加群进一步交流，如无其它问题，此issue将被关闭。
